/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LicenseFeature = IDL.Record({
  'id' : IDL.Text,
  'featureType' : IDL.Text,
  'licenseReferenceName' : IDL.Text,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'priceInCents' : IDL.Nat,
});
export const LicenseBundle = IDL.Record({
  'bundleId' : IDL.Text,
  'name' : IDL.Text,
  'priceInCentsAnnual' : IDL.Nat,
  'featureIds' : IDL.Vec(IDL.Text),
  'headline' : IDL.Text,
  'bullets' : IDL.Vec(IDL.Text),
  'badge' : IDL.Text,
  'saveTextOverride' : IDL.Text,
  'disclaimer' : IDL.Text,
  'alaCarteSumCents' : IDL.Nat,
  'savingsCents' : IDL.Nat,
  'isActive' : IDL.Bool,
  'sortOrder' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'priceInCents' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const InstallerDownloadResult = IDL.Variant({
  'ok' : IDL.Record({
    'file' : ExternalBlob,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const AdminRole = IDL.Variant({
  'licenseGenerator' : IDL.Null,
  'superAdmin' : IDL.Null,
  'featuresManager' : IDL.Null,
  'administrator' : IDL.Null,
});
export const LicenseRequest = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'deliveryMethod' : IDL.Text,
  'expirationDate' : IDL.Int,
  'recipientEmail' : IDL.Text,
});
export const ActivateEntitlementRequest = IDL.Record({
  'entitlementId' : IDL.Text,
  'machineDigest' : IDL.Text,
  'activationNonce' : IDL.Text,
});
export const EntitlementStatusView = IDL.Record({
  'entitlementId' : IDL.Text,
  'email' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'status' : IDL.Text,
  'activationDeadlineIso' : IDL.Text,
  'activatedAtIso' : IDL.Opt(IDL.Text),
  'expiresIso' : IDL.Opt(IDL.Text),
  'machineBindingDigest' : IDL.Opt(IDL.Text),
  'activationNonce' : IDL.Text,
});
export const LinkedPremiumPurchaseView = IDL.Record({
  'transactionId' : IDL.Text,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Nat,
  'status' : IDL.Text,
  'paymentConfirmation' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'customerName' : IDL.Text,
  'purchasedAtIso' : IDL.Text,
  'entitlementId' : IDL.Text,
});
export const EntitlementWorkflowStep = IDL.Record({
  'step' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const EntitlementRegistryEntry = IDL.Record({
  'entitlement' : EntitlementStatusView,
  'purchasedAtIso' : IDL.Text,
  'updatedAtIso' : IDL.Text,
  'linkedPurchases' : IDL.Vec(LinkedPremiumPurchaseView),
  'workflowSteps' : IDL.Vec(EntitlementWorkflowStep),
});
export const LicensingPolicy = IDL.Record({
  'activationWindowDays' : IDL.Int,
  'licenseTermDays' : IDL.Int,
  'machineBindingAlgorithm' : IDL.Text,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'actorRole' : IDL.Text,
  'target' : IDL.Text,
  'timestamp' : IDL.Int,
  'actorEmail' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const EmailAutomationSettings = IDL.Record({
  'emailSubject' : IDL.Text,
  'emailBody' : IDL.Text,
});
export const EmailLog = IDL.Record({
  'sentTimestamp' : IDL.Int,
  'subject' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'deliveryStatus' : IDL.Text,
  'email' : IDL.Text,
});
export const LicenseRecord = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'deliveryStatus' : IDL.Text,
  'expirationDate' : IDL.Int,
  'licenseJson' : IDL.Text,
  'generatedTimestamp' : IDL.Int,
  'recipientEmail' : IDL.Text,
});
export const PremiumPurchase = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'paymentConfirmation' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
  'entitlementId' : IDL.Text,
});
export const ResendConfiguration = IDL.Record({
  'serviceName' : IDL.Text,
  'baseUrl' : IDL.Text,
  'apiKey' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'amountTotal' : IDL.Nat,
    'sessionId' : IDL.Text,
    'bamm_transaction_id' : IDL.Text,
    'customerEmail' : IDL.Text,
  }),
  'err' : IDL.Text,
});
export const PipelineStep = IDL.Record({
  'step' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const TransactionLog = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'licenseStatus' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'amountPaid' : IDL.Text,
  'updatedAt' : IDL.Int,
  'pipelineSteps' : IDL.Vec(PipelineStep),
  'recipientEmail' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const UserSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'downloadCount' : IDL.Nat,
});
export const AdminStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'deactivated' : IDL.Null,
});
export const AdminRecordPublic = IDL.Record({
  'id' : IDL.Text,
  'status' : AdminStatus,
  'principal' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'role' : AdminRole,
  'invitedAt' : IDL.Int,
  'invitedBy' : IDL.Text,
  'email' : IDL.Text,
  'isProtected' : IDL.Bool,
  'lastLogin' : IDL.Opt(IDL.Int),
});
export const EmailSendResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateEntitlement' : IDL.Func(
      [ActivateEntitlementRequest],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'addLicenseFeature' : IDL.Func([LicenseFeature], [], []),
  'addLicenseBundle' : IDL.Func([LicenseBundle], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSuperAdmin' : IDL.Func([IDL.Text], [Result], []),
  'bootstrapSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'checkAnyPendingInvite' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'role' : IDL.Text,
            'email' : IDL.Opt(IDL.Text),
            'hasUnlinked' : IDL.Bool,
          })
        ),
      ],
      ['query'],
    ),
  'checkMyPendingInvite' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }))],
      ['query'],
    ),
  'claimAdminInvite' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'claimRoleElevation' : IDL.Func([IDL.Text], [Result], []),
  'claimSuperAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateAdmin' : IDL.Func([IDL.Text], [Result], []),
  'deleteAdmin' : IDL.Func([IDL.Text], [Result], []),
  'deleteEmailLog' : IDL.Func([IDL.Text], [], []),
  'deleteEmailLogs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'deleteLicenseFeature' : IDL.Func([IDL.Text], [], []),
  'deleteLicenseBundle' : IDL.Func([IDL.Text], [], []),
  'deleteLicenseRecord' : IDL.Func([IDL.Text], [], []),
  'deleteLicenseRecords' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'deletePremiumPurchase' : IDL.Func([IDL.Text], [Result_3], []),
  'deletePremiumPurchases' : IDL.Func([IDL.Vec(IDL.Text)], [Result_2], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteTransactionLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteTransactionLogs' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'deleteUserSubmission' : IDL.Func([IDL.Text], [], []),
  'disableFeature' : IDL.Func([IDL.Text], [], []),
  'downloadMacInstaller' : IDL.Func([], [InstallerDownloadResult], ['query']),
  'downloadWindowsInstaller' : IDL.Func(
      [],
      [InstallerDownloadResult],
      ['query'],
    ),
  'elevateAdminRole' : IDL.Func([IDL.Text, AdminRole], [Result], []),
  'enableFeature' : IDL.Func([IDL.Text], [], []),
  'fulfillPaidLicense' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'generateAndSendPaidLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'generateLicense' : IDL.Func([LicenseRequest], [IDL.Text], []),
  'getActiveFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
  'getActivePremiumProductNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfigurationStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'stripeConfigured' : IDL.Bool,
          'privateKeyPresent' : IDL.Bool,
          'resendConfigured' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getCoreFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
  'getCustomerEntitlements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EntitlementStatusView)],
      ['query'],
    ),
  'getEmailAutomationSettings' : IDL.Func(
      [],
      [EmailAutomationSettings],
      ['query'],
    ),
  'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
  'getEntitlementRegistry' : IDL.Func(
      [],
      [IDL.Vec(EntitlementRegistryEntry)],
      ['query'],
    ),
  'getInstallerFileNames' : IDL.Func(
      [],
      [
        IDL.Record({
          'macFileName' : IDL.Opt(IDL.Text),
          'windowsFileName' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'backfillEntitlementsFromPurchases' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'created' : IDL.Nat,
            'linked' : IDL.Nat,
            'skippedAlreadyLinked' : IDL.Nat,
            'skippedNoFeatures' : IDL.Nat,
            'skippedIneligibleStatus' : IDL.Nat,
            'registrySize' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getEntitlementStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : EntitlementStatusView, 'err' : IDL.Text })],
      ['query'],
    ),
  'getLicenseFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
  'getLicenseBundles' : IDL.Func([], [IDL.Vec(LicenseBundle)], ['query']),
  'getAllLicenseBundles' : IDL.Func([], [IDL.Vec(LicenseBundle)], ['query']),
  'getLicenseRecords' : IDL.Func([], [IDL.Vec(LicenseRecord)], ['query']),
  'getLicenseReferenceNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLicensingPolicy' : IDL.Func([], [LicensingPolicy], ['query']),
  'getMacInstallerFile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'file' : ExternalBlob,
            'mimeType' : IDL.Text,
            'fileName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getMyAdminRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPremiumFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
  'getPremiumPurchases' : IDL.Func([], [IDL.Vec(PremiumPurchase)], ['query']),
  'getPrivateKeyFile' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getPrivateKeyForSigning' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getResendConfiguration' : IDL.Func(
      [],
      [IDL.Opt(ResendConfiguration)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [Result_1], []),
  'getSuperAdminClaimCode' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactionLogs' : IDL.Func([], [IDL.Vec(TransactionLog)], ['query']),
  'getTrialEligibleProductNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTrialLicenseFile' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getTrialLicensePayload' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func([], [IDL.Vec(UserSubmission)], ['query']),
  'getWindowsInstallerFile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'file' : ExternalBlob,
            'mimeType' : IDL.Text,
            'fileName' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'incrementDownloadCount' : IDL.Func([IDL.Text], [], []),
  'initializeDefaultPremiumFeatures' : IDL.Func([], [], []),
  'initializeDefaultLicenseBundles' : IDL.Func([], [], []),
  'inviteAdmin' : IDL.Func([IDL.Text, IDL.Text, AdminRole], [Result], []),
  'isAdminByRole' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(AdminRecordPublic)], []),
  'logEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'migrateFeatureNames' : IDL.Func([], [IDL.Text], []),
  'reactivateAdmin' : IDL.Func([IDL.Text], [Result], []),
  'recordLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int, IDL.Text],
      [],
      [],
    ),
  'recordPremiumPurchase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'regenerateSuperAdminClaimCode' : IDL.Func([], [Result], []),
  'removeFeatureImage' : IDL.Func([IDL.Text], [], []),
  'resendPurchaseLicense' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resendTrialLicense' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendManualLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [EmailSendResult],
      [],
    ),
  'sendSignedPaidLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendSignedTrialLicenseEmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'sendTrialLicenseEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setResendConfiguration' : IDL.Func([ResendConfiguration], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'alreadySubmitted' : IDL.Record({ 'email' : IDL.Text }),
          'newUser' : IDL.Record({ 'message' : IDL.Text }),
        }),
      ],
      [],
    ),
  'testResendConnection' : IDL.Func([], [EmailSendResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminRole' : IDL.Func([IDL.Text, AdminRole], [Result], []),
  'updateEmailAutomationSettings' : IDL.Func([EmailAutomationSettings], [], []),
  'updateFeatureStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateLicenseFeature' : IDL.Func([LicenseFeature], [], []),
  'updateLicenseBundle' : IDL.Func([LicenseBundle], [], []),
  'updateBundleStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updatePurchaseFeatures' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateResendServiceName' : IDL.Func([IDL.Text], [], []),
  'uploadFeatureImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadMacInstaller' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Bool], []),
  'uploadPrivateKeyFile' : IDL.Func([ExternalBlob], [], []),
  'uploadTrialLicenseFile' : IDL.Func([ExternalBlob], [], []),
  'uploadWindowsInstaller' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LicenseFeature = IDL.Record({
    'id' : IDL.Text,
    'featureType' : IDL.Text,
    'licenseReferenceName' : IDL.Text,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'priceInCents' : IDL.Nat,
  });
  const LicenseBundle = IDL.Record({
    'bundleId' : IDL.Text,
    'name' : IDL.Text,
    'priceInCentsAnnual' : IDL.Nat,
    'featureIds' : IDL.Vec(IDL.Text),
    'headline' : IDL.Text,
    'bullets' : IDL.Vec(IDL.Text),
    'badge' : IDL.Text,
    'saveTextOverride' : IDL.Text,
    'disclaimer' : IDL.Text,
    'alaCarteSumCents' : IDL.Nat,
    'savingsCents' : IDL.Nat,
    'isActive' : IDL.Bool,
    'sortOrder' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'priceInCents' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const InstallerDownloadResult = IDL.Variant({
    'ok' : IDL.Record({
      'file' : ExternalBlob,
      'mimeType' : IDL.Text,
      'fileName' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const AdminRole = IDL.Variant({
    'licenseGenerator' : IDL.Null,
    'superAdmin' : IDL.Null,
    'featuresManager' : IDL.Null,
    'administrator' : IDL.Null,
  });
  const LicenseRequest = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'deliveryMethod' : IDL.Text,
    'expirationDate' : IDL.Int,
    'recipientEmail' : IDL.Text,
  });
  const ActivateEntitlementRequest = IDL.Record({
    'entitlementId' : IDL.Text,
    'machineDigest' : IDL.Text,
    'activationNonce' : IDL.Text,
  });
  const EntitlementStatusView = IDL.Record({
    'entitlementId' : IDL.Text,
    'email' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'status' : IDL.Text,
    'activationDeadlineIso' : IDL.Text,
    'activatedAtIso' : IDL.Opt(IDL.Text),
    'expiresIso' : IDL.Opt(IDL.Text),
    'machineBindingDigest' : IDL.Opt(IDL.Text),
    'activationNonce' : IDL.Text,
  });
  const LinkedPremiumPurchaseView = IDL.Record({
    'transactionId' : IDL.Text,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Nat,
    'status' : IDL.Text,
    'paymentConfirmation' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'customerName' : IDL.Text,
    'purchasedAtIso' : IDL.Text,
    'entitlementId' : IDL.Text,
  });
  const EntitlementWorkflowStep = IDL.Record({
    'step' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const EntitlementRegistryEntry = IDL.Record({
    'entitlement' : EntitlementStatusView,
    'purchasedAtIso' : IDL.Text,
    'updatedAtIso' : IDL.Text,
    'linkedPurchases' : IDL.Vec(LinkedPremiumPurchaseView),
    'workflowSteps' : IDL.Vec(EntitlementWorkflowStep),
  });
  const LicensingPolicy = IDL.Record({
    'activationWindowDays' : IDL.Int,
    'licenseTermDays' : IDL.Int,
    'machineBindingAlgorithm' : IDL.Text,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'actorRole' : IDL.Text,
    'target' : IDL.Text,
    'timestamp' : IDL.Int,
    'actorEmail' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const EmailAutomationSettings = IDL.Record({
    'emailSubject' : IDL.Text,
    'emailBody' : IDL.Text,
  });
  const EmailLog = IDL.Record({
    'sentTimestamp' : IDL.Int,
    'subject' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'deliveryStatus' : IDL.Text,
    'email' : IDL.Text,
  });
  const LicenseRecord = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'deliveryStatus' : IDL.Text,
    'expirationDate' : IDL.Int,
    'licenseJson' : IDL.Text,
    'generatedTimestamp' : IDL.Int,
    'recipientEmail' : IDL.Text,
  });
  const PremiumPurchase = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'paymentConfirmation' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
    'entitlementId' : IDL.Text,
  });
  const ResendConfiguration = IDL.Record({
    'serviceName' : IDL.Text,
    'baseUrl' : IDL.Text,
    'apiKey' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({
      'customerName' : IDL.Text,
      'status' : IDL.Text,
      'features' : IDL.Vec(IDL.Text),
      'amountTotal' : IDL.Nat,
      'sessionId' : IDL.Text,
      'bamm_transaction_id' : IDL.Text,
      'customerEmail' : IDL.Text,
    }),
    'err' : IDL.Text,
  });
  const PipelineStep = IDL.Record({
    'step' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const TransactionLog = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'licenseStatus' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'amountPaid' : IDL.Text,
    'updatedAt' : IDL.Int,
    'pipelineSteps' : IDL.Vec(PipelineStep),
    'recipientEmail' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const UserSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'downloadCount' : IDL.Nat,
  });
  const AdminStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'deactivated' : IDL.Null,
  });
  const AdminRecordPublic = IDL.Record({
    'id' : IDL.Text,
    'status' : AdminStatus,
    'principal' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'role' : AdminRole,
    'invitedAt' : IDL.Int,
    'invitedBy' : IDL.Text,
    'email' : IDL.Text,
    'isProtected' : IDL.Bool,
    'lastLogin' : IDL.Opt(IDL.Int),
  });
  const EmailSendResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateEntitlement' : IDL.Func(
        [ActivateEntitlementRequest],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'addLicenseFeature' : IDL.Func([LicenseFeature], [], []),
    'addLicenseBundle' : IDL.Func([LicenseBundle], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSuperAdmin' : IDL.Func([IDL.Text], [Result], []),
    'bootstrapSuperAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'checkAnyPendingInvite' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'role' : IDL.Text,
              'email' : IDL.Opt(IDL.Text),
              'hasUnlinked' : IDL.Bool,
            })
          ),
        ],
        ['query'],
      ),
    'checkMyPendingInvite' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }))],
        ['query'],
      ),
    'claimAdminInvite' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'claimRoleElevation' : IDL.Func([IDL.Text], [Result], []),
    'claimSuperAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateAdmin' : IDL.Func([IDL.Text], [Result], []),
    'deleteAdmin' : IDL.Func([IDL.Text], [Result], []),
    'deleteEmailLog' : IDL.Func([IDL.Text], [], []),
    'deleteEmailLogs' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'deleteLicenseFeature' : IDL.Func([IDL.Text], [], []),
    'deleteLicenseBundle' : IDL.Func([IDL.Text], [], []),
    'deleteLicenseRecord' : IDL.Func([IDL.Text], [], []),
    'deleteLicenseRecords' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'deletePremiumPurchase' : IDL.Func([IDL.Text], [Result_3], []),
    'deletePremiumPurchases' : IDL.Func([IDL.Vec(IDL.Text)], [Result_2], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteTransactionLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteTransactionLogs' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'deleteUserSubmission' : IDL.Func([IDL.Text], [], []),
    'disableFeature' : IDL.Func([IDL.Text], [], []),
    'downloadMacInstaller' : IDL.Func([], [InstallerDownloadResult], ['query']),
    'downloadWindowsInstaller' : IDL.Func(
        [],
        [InstallerDownloadResult],
        ['query'],
      ),
    'elevateAdminRole' : IDL.Func([IDL.Text, AdminRole], [Result], []),
    'enableFeature' : IDL.Func([IDL.Text], [], []),
    'fulfillPaidLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'generateAndSendPaidLicense' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Float64,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'generateLicense' : IDL.Func([LicenseRequest], [IDL.Text], []),
    'getActiveFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
    'getActivePremiumProductNames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfigurationStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'stripeConfigured' : IDL.Bool,
            'privateKeyPresent' : IDL.Bool,
            'resendConfigured' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getCoreFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
    'getCustomerEntitlements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EntitlementStatusView)],
        ['query'],
      ),
    'getEmailAutomationSettings' : IDL.Func(
        [],
        [EmailAutomationSettings],
        ['query'],
      ),
    'getEmailLogs' : IDL.Func([], [IDL.Vec(EmailLog)], ['query']),
    'getEntitlementRegistry' : IDL.Func(
        [],
        [IDL.Vec(EntitlementRegistryEntry)],
        ['query'],
      ),
    'getInstallerFileNames' : IDL.Func(
        [],
        [
          IDL.Record({
            'macFileName' : IDL.Opt(IDL.Text),
            'windowsFileName' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'backfillEntitlementsFromPurchases' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'created' : IDL.Nat,
              'linked' : IDL.Nat,
              'skippedAlreadyLinked' : IDL.Nat,
              'skippedNoFeatures' : IDL.Nat,
              'skippedIneligibleStatus' : IDL.Nat,
              'registrySize' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getEntitlementStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : EntitlementStatusView, 'err' : IDL.Text })],
        ['query'],
      ),
    'getLicenseFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
    'getLicenseBundles' : IDL.Func([], [IDL.Vec(LicenseBundle)], ['query']),
    'getAllLicenseBundles' : IDL.Func([], [IDL.Vec(LicenseBundle)], ['query']),
    'getLicenseRecords' : IDL.Func([], [IDL.Vec(LicenseRecord)], ['query']),
    'getLicenseReferenceNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLicensingPolicy' : IDL.Func([], [LicensingPolicy], ['query']),
    'getMacInstallerFile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'file' : ExternalBlob,
              'mimeType' : IDL.Text,
              'fileName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getMyAdminRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPremiumFeatures' : IDL.Func([], [IDL.Vec(LicenseFeature)], ['query']),
    'getPremiumPurchases' : IDL.Func([], [IDL.Vec(PremiumPurchase)], ['query']),
    'getPrivateKeyFile' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getPrivateKeyForSigning' : IDL.Func(
        [],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getResendConfiguration' : IDL.Func(
        [],
        [IDL.Opt(ResendConfiguration)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [Result_1], []),
    'getSuperAdminClaimCode' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactionLogs' : IDL.Func([], [IDL.Vec(TransactionLog)], ['query']),
    'getTrialEligibleProductNames' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getTrialLicenseFile' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getTrialLicensePayload' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func([], [IDL.Vec(UserSubmission)], ['query']),
    'getWindowsInstallerFile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'file' : ExternalBlob,
              'mimeType' : IDL.Text,
              'fileName' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'incrementDownloadCount' : IDL.Func([IDL.Text], [], []),
    'initializeDefaultPremiumFeatures' : IDL.Func([], [], []),
    'initializeDefaultLicenseBundles' : IDL.Func([], [], []),
    'inviteAdmin' : IDL.Func([IDL.Text, IDL.Text, AdminRole], [Result], []),
    'isAdminByRole' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(AdminRecordPublic)], []),
    'logEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'migrateFeatureNames' : IDL.Func([], [IDL.Text], []),
    'reactivateAdmin' : IDL.Func([IDL.Text], [Result], []),
    'recordLicense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Int, IDL.Text],
        [],
        [],
      ),
    'recordPremiumPurchase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'regenerateSuperAdminClaimCode' : IDL.Func([], [Result], []),
    'removeFeatureImage' : IDL.Func([IDL.Text], [], []),
    'resendPurchaseLicense' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resendTrialLicense' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendManualLicense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [EmailSendResult],
        [],
      ),
    'sendSignedPaidLicense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendSignedTrialLicenseEmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'sendTrialLicenseEmail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setResendConfiguration' : IDL.Func([ResendConfiguration], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'alreadySubmitted' : IDL.Record({ 'email' : IDL.Text }),
            'newUser' : IDL.Record({ 'message' : IDL.Text }),
          }),
        ],
        [],
      ),
    'testResendConnection' : IDL.Func([], [EmailSendResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminRole' : IDL.Func([IDL.Text, AdminRole], [Result], []),
    'updateEmailAutomationSettings' : IDL.Func(
        [EmailAutomationSettings],
        [],
        [],
      ),
    'updateFeatureStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateLicenseFeature' : IDL.Func([LicenseFeature], [], []),
    'updateLicenseBundle' : IDL.Func([LicenseBundle], [], []),
    'updateBundleStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updatePurchaseFeatures' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateResendServiceName' : IDL.Func([IDL.Text], [], []),
    'uploadFeatureImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadMacInstaller' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Bool], []),
    'uploadPrivateKeyFile' : IDL.Func([ExternalBlob], [], []),
    'uploadTrialLicenseFile' : IDL.Func([ExternalBlob], [], []),
    'uploadWindowsInstaller' : IDL.Func(
        [ExternalBlob, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };