/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminRecordPublic {
  'id' : string,
  'status' : AdminStatus,
  'principal' : [] | [Principal],
  'name' : string,
  'role' : AdminRole,
  'invitedAt' : bigint,
  'invitedBy' : string,
  'email' : string,
  'isProtected' : boolean,
  'lastLogin' : [] | [bigint],
}
export type AdminRole = { 'licenseGenerator' : null } |
  { 'superAdmin' : null } |
  { 'featuresManager' : null } |
  { 'administrator' : null };
export type AdminStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'deactivated' : null };
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'actorRole' : string,
  'target' : string,
  'timestamp' : bigint,
  'actorEmail' : string,
}
export interface EmailAutomationSettings {
  'emailSubject' : string,
  'emailBody' : string,
}
export interface EmailLog {
  'sentTimestamp' : bigint,
  'subject' : string,
  'errorMessage' : [] | [string],
  'deliveryStatus' : string,
  'email' : string,
}
export type EmailSendResult = { 'ok' : string } |
  { 'err' : string };
export type ExternalBlob = Uint8Array;
export type InstallerDownloadResult = {
    'ok' : { 'file' : ExternalBlob, 'mimeType' : string, 'fileName' : string }
  } |
  { 'err' : string };
export interface LicenseFeature {
  'id' : string,
  'featureType' : string,
  'licenseReferenceName' : string,
  'isPremium' : boolean,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'image' : [] | [ExternalBlob],
  'priceInCents' : bigint,
}
export interface LicenseBundle {
  'bundleId' : string,
  'name' : string,
  'priceInCentsAnnual' : bigint,
  'featureIds' : Array<string>,
  'headline' : string,
  'bullets' : Array<string>,
  'badge' : string,
  'saveTextOverride' : string,
  'disclaimer' : string,
  'alaCarteSumCents' : bigint,
  'savingsCents' : bigint,
  'isActive' : boolean,
  'sortOrder' : bigint,
}
export interface LicenseRecord {
  'features' : Array<string>,
  'deliveryStatus' : string,
  'expirationDate' : bigint,
  'licenseJson' : string,
  'generatedTimestamp' : bigint,
  'recipientEmail' : string,
}
export interface ActivateEntitlementRequest {
  'entitlementId' : string,
  'machineDigest' : string,
  'activationNonce' : string,
}
export interface EntitlementStatusView {
  'entitlementId' : string,
  'email' : string,
  'features' : Array<string>,
  'status' : string,
  'activationDeadlineIso' : string,
  'activatedAtIso' : [] | [string],
  'expiresIso' : [] | [string],
  'machineBindingDigest' : [] | [string],
  'activationNonce' : string,
}
export interface LinkedPremiumPurchaseView {
  'transactionId' : string,
  'stripeSessionId' : string,
  'amount' : bigint,
  'status' : string,
  'paymentConfirmation' : string,
  'features' : Array<string>,
  'customerName' : string,
  'purchasedAtIso' : string,
  'entitlementId' : string,
}
export interface EntitlementWorkflowStep {
  'step' : string,
  'message' : string,
  'timestamp' : bigint,
  'stripeSessionId' : [] | [string],
}
export interface EntitlementRegistryEntry {
  'entitlement' : EntitlementStatusView,
  'purchasedAtIso' : string,
  'updatedAtIso' : string,
  'linkedPurchases' : Array<LinkedPremiumPurchaseView>,
  'workflowSteps' : Array<EntitlementWorkflowStep>,
}
export interface LicensingPolicy {
  'activationWindowDays' : bigint,
  'licenseTermDays' : bigint,
  'machineBindingAlgorithm' : string,
}
export interface LicenseRequest {
  'features' : Array<string>,
  'deliveryMethod' : string,
  'expirationDate' : bigint,
  'recipientEmail' : string,
}
export interface PipelineStep {
  'step' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface PremiumPurchase {
  'customerName' : string,
  'status' : string,
  'features' : Array<string>,
  'paymentConfirmation' : string,
  'email' : string,
  'timestamp' : bigint,
  'stripeSessionId' : string,
  'amount' : bigint,
  'transactionId' : string,
  'entitlementId' : string,
}
export interface Product {
  'id' : string,
  'isPremium' : boolean,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
  'currency' : string,
  'priceInCents' : bigint,
}
export interface ResendConfiguration {
  'serviceName' : string,
  'baseUrl' : string,
  'apiKey' : string,
  'senderEmail' : string,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = {
    'ok' : {
      'customerName' : string,
      'status' : string,
      'features' : Array<string>,
      'amountTotal' : bigint,
      'sessionId' : string,
      'bamm_transaction_id' : string,
      'customerEmail' : string,
    }
  } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export interface TransactionLog {
  'id' : string,
  'customerName' : string,
  'licenseStatus' : string,
  'features' : Array<string>,
  'createdAt' : bigint,
  'amountPaid' : string,
  'updatedAt' : bigint,
  'pipelineSteps' : Array<PipelineStep>,
  'recipientEmail' : string,
  'transactionId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubmission {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'downloadCount' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateEntitlement' : ActorMethod<
    [ActivateEntitlementRequest],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addLicenseFeature' : ActorMethod<[LicenseFeature], undefined>,
  'addLicenseBundle' : ActorMethod<[LicenseBundle], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSuperAdmin' : ActorMethod<[string], Result>,
  'bootstrapSuperAdmin' : ActorMethod<[string, string], string>,
  'checkAnyPendingInvite' : ActorMethod<
    [],
    [] | [{ 'role' : string, 'email' : [] | [string], 'hasUnlinked' : boolean }]
  >,
  'checkMyPendingInvite' : ActorMethod<
    [],
    [] | [{ 'role' : string, 'email' : string }]
  >,
  'claimAdminInvite' : ActorMethod<[string, string], Result>,
  'claimRoleElevation' : ActorMethod<[string], Result>,
  'claimSuperAdmin' : ActorMethod<[string, string, string], Result>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deactivateAdmin' : ActorMethod<[string], Result>,
  'deleteAdmin' : ActorMethod<[string], Result>,
  'deleteEmailLog' : ActorMethod<[string], undefined>,
  'deleteEmailLogs' : ActorMethod<[Array<string>], undefined>,
  'deleteLicenseFeature' : ActorMethod<[string], undefined>,
  'deleteLicenseBundle' : ActorMethod<[string], undefined>,
  'deleteLicenseRecord' : ActorMethod<[string], undefined>,
  'deleteLicenseRecords' : ActorMethod<[Array<string>], undefined>,
  'deletePremiumPurchase' : ActorMethod<[string], Result_3>,
  'deletePremiumPurchases' : ActorMethod<[Array<string>], Result_2>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteTransactionLog' : ActorMethod<[string], boolean>,
  'deleteTransactionLogs' : ActorMethod<[Array<string>], bigint>,
  'deleteUserSubmission' : ActorMethod<[string], undefined>,
  'disableFeature' : ActorMethod<[string], undefined>,
  'downloadMacInstaller' : ActorMethod<[], InstallerDownloadResult>,
  'downloadWindowsInstaller' : ActorMethod<[], InstallerDownloadResult>,
  'elevateAdminRole' : ActorMethod<[string, AdminRole], Result>,
  'enableFeature' : ActorMethod<[string], undefined>,
  'fulfillPaidLicense' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateAndSendPaidLicense' : ActorMethod<
    [string, string, string, string, Array<string>, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateLicense' : ActorMethod<[LicenseRequest], string>,
  'getActiveFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getActivePremiumProductNames' : ActorMethod<[], Array<string>>,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfigurationStatus' : ActorMethod<
    [],
    {
      'stripeConfigured' : boolean,
      'privateKeyPresent' : boolean,
      'resendConfigured' : boolean,
    }
  >,
  'getCoreFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getCustomerEntitlements' : ActorMethod<[string], Array<EntitlementStatusView>>,
  'getEmailAutomationSettings' : ActorMethod<[], EmailAutomationSettings>,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  'getEntitlementRegistry' : ActorMethod<[], Array<EntitlementRegistryEntry>>,
  'getInstallerFileNames' : ActorMethod<
    [],
    { 'macFileName' : [] | [string], 'windowsFileName' : [] | [string] }
  >,
  'backfillEntitlementsFromPurchases' : ActorMethod<
    [],
    { 'ok' : {
        'created' : bigint,
        'linked' : bigint,
        'skippedAlreadyLinked' : bigint,
        'skippedNoFeatures' : bigint,
        'skippedIneligibleStatus' : bigint,
        'registrySize' : bigint,
      } } |
      { 'err' : string }
  >,
  'resetEntitlementActivation' : ActorMethod<
    [string],
    { 'ok' : EntitlementStatusView } |
      { 'err' : string }
  >,
  'getEntitlementStatus' : ActorMethod<
    [string, string],
    { 'ok' : EntitlementStatusView } |
      { 'err' : string }
  >,
  'getLicenseFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getLicenseBundles' : ActorMethod<[], Array<LicenseBundle>>,
  'getAllLicenseBundles' : ActorMethod<[], Array<LicenseBundle>>,
  'getLicenseRecords' : ActorMethod<[], Array<LicenseRecord>>,
  'getLicenseReferenceNames' : ActorMethod<[], Array<string>>,
  'getLicensingPolicy' : ActorMethod<[], LicensingPolicy>,
  'getMacInstallerFile' : ActorMethod<
    [],
    [] | [{ 'file' : ExternalBlob, 'mimeType' : string, 'fileName' : string }]
  >,
  'getMyAdminRole' : ActorMethod<[], [] | [string]>,
  'getPremiumFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getPremiumPurchases' : ActorMethod<[], Array<PremiumPurchase>>,
  'getPrivateKeyFile' : ActorMethod<[], [] | [ExternalBlob]>,
  'getPrivateKeyForSigning' : ActorMethod<[], [] | [ExternalBlob]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getResendConfiguration' : ActorMethod<[], [] | [ResendConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], Result_1>,
  'getSuperAdminClaimCode' : ActorMethod<[], string>,
  'getTransactionLogs' : ActorMethod<[], Array<TransactionLog>>,
  'getTrialEligibleProductNames' : ActorMethod<[], Array<string>>,
  'getTrialLicenseFile' : ActorMethod<[], [] | [ExternalBlob]>,
  'getTrialLicensePayload' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[], Array<UserSubmission>>,
  'getWindowsInstallerFile' : ActorMethod<
    [],
    [] | [{ 'file' : ExternalBlob, 'mimeType' : string, 'fileName' : string }]
  >,
  'incrementDownloadCount' : ActorMethod<[string], undefined>,
  'initializeDefaultPremiumFeatures' : ActorMethod<[], undefined>,
  'initializeDefaultLicenseBundles' : ActorMethod<[], undefined>,
  'inviteAdmin' : ActorMethod<[string, string, AdminRole], Result>,
  'isAdminByRole' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<AdminRecordPublic>>,
  'logEmail' : ActorMethod<[string, string, string], undefined>,
  'migrateFeatureNames' : ActorMethod<[], string>,
  'reactivateAdmin' : ActorMethod<[string], Result>,
  'recordLicense' : ActorMethod<
    [string, string, Array<string>, bigint, string],
    undefined
  >,
  'recordPremiumPurchase' : ActorMethod<
    [string, string, bigint, string, string, string, string, Array<string>],
    undefined
  >,
  'regenerateSuperAdminClaimCode' : ActorMethod<[], Result>,
  'removeFeatureImage' : ActorMethod<[string], undefined>,
  'resendPurchaseLicense' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resendTrialLicense' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendManualLicense' : ActorMethod<
    [string, string, Array<string>],
    EmailSendResult
  >,
  'sendSignedPaidLicense' : ActorMethod<
    [string, string, string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendSignedTrialLicenseEmail' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'sendTrialLicenseEmail' : ActorMethod<[string, string, string], undefined>,
  'setResendConfiguration' : ActorMethod<[ResendConfiguration], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitUser' : ActorMethod<
    [string, string],
    { 'alreadySubmitted' : { 'email' : string } } |
      { 'newUser' : { 'message' : string } }
  >,
  'testResendConnection' : ActorMethod<[], EmailSendResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminRole' : ActorMethod<[string, AdminRole], Result>,
  'updateEmailAutomationSettings' : ActorMethod<
    [EmailAutomationSettings],
    undefined
  >,
  'updateFeatureStatus' : ActorMethod<[string, boolean], undefined>,
  'updateLicenseFeature' : ActorMethod<[LicenseFeature], undefined>,
  'updateLicenseBundle' : ActorMethod<[LicenseBundle], undefined>,
  'updateBundleStatus' : ActorMethod<[string, boolean], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updatePurchaseFeatures' : ActorMethod<
    [string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateResendServiceName' : ActorMethod<[string], undefined>,
  'uploadFeatureImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadMacInstaller' : ActorMethod<[ExternalBlob, string], boolean>,
  'uploadPrivateKeyFile' : ActorMethod<[ExternalBlob], undefined>,
  'uploadTrialLicenseFile' : ActorMethod<[ExternalBlob], undefined>,
  'uploadWindowsInstaller' : ActorMethod<[ExternalBlob, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];