/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivateEntitlementRequest {
  'entitlementId' : string,
  'activationNonce' : string,
  'machineDigest' : string,
}
export interface AdminRecordPublic {
  'id' : string,
  'status' : AdminStatus,
  'principal' : [] | [Principal],
  'name' : string,
  'role' : AdminRole,
  'invitedAt' : bigint,
  'invitedBy' : string,
  'email' : string,
  'isProtected' : boolean,
  'lastLogin' : [] | [bigint],
}
export type AdminRole = { 'licenseGenerator' : null } |
  { 'superAdmin' : null } |
  { 'featuresManager' : null } |
  { 'administrator' : null };
export type AdminStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'deactivated' : null };
export interface AuditEntry {
  'id' : string,
  'action' : string,
  'actorRole' : string,
  'target' : string,
  'timestamp' : bigint,
  'actorEmail' : string,
}
export interface EmailAutomationSettings {
  'emailSubject' : string,
  'emailBody' : string,
}
export interface EmailLog {
  'sentTimestamp' : bigint,
  'subject' : string,
  'errorMessage' : [] | [string],
  'deliveryStatus' : string,
  'email' : string,
}
export type EmailSendResult = { 'ok' : string } |
  { 'err' : string };
export interface EntitlementRegistryEntry {
  'purchasedAtIso' : string,
  'linkedPurchases' : Array<LinkedPremiumPurchaseView>,
  'updatedAtIso' : string,
  'workflowSteps' : Array<EntitlementWorkflowStep>,
  'entitlement' : EntitlementStatusView,
}
export interface EntitlementStatusView {
  'status' : string,
  'features' : Array<string>,
  'entitlementId' : string,
  'activationDeadlineIso' : string,
  'email' : string,
  'machineBindingDigest' : [] | [string],
  'activationNonce' : string,
  'expiresIso' : [] | [string],
  'activatedAtIso' : [] | [string],
}
export interface EntitlementWorkflowStep {
  'step' : string,
  'message' : string,
  'timestamp' : bigint,
  'stripeSessionId' : [] | [string],
}
export type InstallerChunkResult = {
    'ok' : {
      'chunkIndex' : bigint,
      'chunk' : Uint8Array,
      'chunkCount' : bigint,
    }
  } |
  { 'err' : string };
export type InstallerDownloadResult = {
    'ok' : { 'file' : Uint8Array, 'mimeType' : string, 'fileName' : string }
  } |
  { 'err' : string };
export interface InstallerMeta {
  'mimeType' : string,
  'fileName' : string,
  'totalSize' : bigint,
  'chunkCount' : bigint,
}
export interface LicenseBundle {
  'featureIds' : Array<string>,
  'priceInCentsAnnual' : bigint,
  'bullets' : Array<string>,
  'sortOrder' : bigint,
  'headline' : string,
  'name' : string,
  'isActive' : boolean,
  'saveTextOverride' : string,
  'savingsCents' : bigint,
  'badge' : string,
  'disclaimer' : string,
  'bundleId' : string,
  'alaCarteSumCents' : bigint,
}
export interface LicenseFeature {
  'id' : string,
  'featureType' : string,
  'licenseReferenceName' : string,
  'isPremium' : boolean,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'image' : [] | [Uint8Array],
  'priceInCents' : bigint,
}
export interface LicenseRecord {
  'features' : Array<string>,
  'deliveryStatus' : string,
  'expirationDate' : bigint,
  'licenseJson' : string,
  'generatedTimestamp' : bigint,
  'recipientEmail' : string,
}
export interface LicenseRequest {
  'features' : Array<string>,
  'deliveryMethod' : string,
  'expirationDate' : bigint,
  'recipientEmail' : string,
}
export interface LinkedPremiumPurchaseView {
  'customerName' : string,
  'purchasedAtIso' : string,
  'status' : string,
  'features' : Array<string>,
  'entitlementId' : string,
  'paymentConfirmation' : string,
  'stripeSessionId' : string,
  'amount' : bigint,
  'transactionId' : string,
}
export interface PipelineStep {
  'step' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface PremiumPurchase {
  'customerName' : string,
  'status' : string,
  'features' : Array<string>,
  'entitlementId' : string,
  'paymentConfirmation' : string,
  'email' : string,
  'timestamp' : bigint,
  'stripeSessionId' : string,
  'amount' : bigint,
  'transactionId' : string,
}
export interface Product {
  'id' : string,
  'isPremium' : boolean,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
  'currency' : string,
  'priceInCents' : bigint,
}
export interface ResendConfiguration {
  'serviceName' : string,
  'baseUrl' : string,
  'apiKey' : string,
  'senderEmail' : string,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = {
    'ok' : {
      'customerName' : string,
      'status' : string,
      'features' : Array<string>,
      'amountTotal' : bigint,
      'sessionId' : string,
      'bamm_transaction_id' : string,
      'customerEmail' : string,
    }
  } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export interface TransactionLog {
  'id' : string,
  'customerName' : string,
  'licenseStatus' : string,
  'features' : Array<string>,
  'createdAt' : bigint,
  'amountPaid' : string,
  'updatedAt' : bigint,
  'pipelineSteps' : Array<PipelineStep>,
  'recipientEmail' : string,
  'transactionId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSubmission {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'downloadCount' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activateEntitlement' : ActorMethod<
    [ActivateEntitlementRequest],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addLicenseBundle' : ActorMethod<[LicenseBundle], undefined>,
  'addLicenseFeature' : ActorMethod<[LicenseFeature], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSuperAdmin' : ActorMethod<[string], Result>,
  /**
   * / One-time admin backfill: create CustomerEntitlement rows from historical premiumPurchases.
   * / Stable upgrade only blanked PremiumPurchase.entitlementId (DDR-016); it never populated
   * / entitlementsByEmail. Eligible purchase.status: paid_sent / paid / complete / confirmed
   * / (fulfillment writes "confirmed" before email; many live rows stay there). Also accept
   * / paymentConfirmation == "paid" when status is ambiguous. Skips rows that already have a
   * / non-empty entitlementId. Fresh activation window starts at backfill time so old purchase
   * / timestamps do not instantly forfeit. Does not re-email licenses.
   */
  'backfillEntitlementsFromPurchases' : ActorMethod<
    [],
    {
        'ok' : {
          'registrySize' : bigint,
          'created' : bigint,
          'skippedNoFeatures' : bigint,
          'skippedIneligibleStatus' : bigint,
          'skippedAlreadyLinked' : bigint,
          'linked' : bigint,
        }
      } |
      { 'err' : string }
  >,
  'beginMacInstallerUpload' : ActorMethod<[string, bigint, bigint], Result>,
  'beginWindowsInstallerUpload' : ActorMethod<[string, bigint, bigint], Result>,
  'bootstrapSuperAdmin' : ActorMethod<[string, string], string>,
  'cancelMacInstallerUpload' : ActorMethod<[], undefined>,
  'cancelWindowsInstallerUpload' : ActorMethod<[], undefined>,
  'checkAnyPendingInvite' : ActorMethod<
    [],
    [] | [{ 'role' : string, 'email' : [] | [string], 'hasUnlinked' : boolean }]
  >,
  'checkMyPendingInvite' : ActorMethod<
    [],
    [] | [{ 'role' : string, 'email' : string }]
  >,
  'claimAdminInvite' : ActorMethod<[string, string], Result>,
  'claimRoleElevation' : ActorMethod<[string], Result>,
  'claimSuperAdmin' : ActorMethod<[string, string, string], Result>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deactivateAdmin' : ActorMethod<[string], Result>,
  'deleteAdmin' : ActorMethod<[string], Result>,
  'deleteEmailLog' : ActorMethod<[string], undefined>,
  'deleteEmailLogs' : ActorMethod<[Array<string>], undefined>,
  'deleteLicenseBundle' : ActorMethod<[string], undefined>,
  'deleteLicenseFeature' : ActorMethod<[string], undefined>,
  'deleteLicenseRecord' : ActorMethod<[string], undefined>,
  'deleteLicenseRecords' : ActorMethod<[Array<string>], undefined>,
  'deletePremiumPurchase' : ActorMethod<[string], Result_3>,
  'deletePremiumPurchases' : ActorMethod<[Array<string>], Result_2>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteTransactionLog' : ActorMethod<[string], boolean>,
  'deleteTransactionLogs' : ActorMethod<[Array<string>], bigint>,
  'deleteUserSubmission' : ActorMethod<[string], undefined>,
  'disableFeature' : ActorMethod<[string], undefined>,
  'downloadMacInstaller' : ActorMethod<[], InstallerDownloadResult>,
  'downloadMacInstallerChunk' : ActorMethod<[bigint], InstallerChunkResult>,
  'downloadWindowsInstaller' : ActorMethod<[], InstallerDownloadResult>,
  'downloadWindowsInstallerChunk' : ActorMethod<[bigint], InstallerChunkResult>,
  'elevateAdminRole' : ActorMethod<[string, AdminRole], Result>,
  'enableFeature' : ActorMethod<[string], undefined>,
  'finalizeMacInstallerUpload' : ActorMethod<[], Result>,
  'finalizeWindowsInstallerUpload' : ActorMethod<[], Result>,
  'fulfillPaidLicense' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateAndSendPaidLicense' : ActorMethod<
    [string, string, string, string, Array<string>, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateLicense' : ActorMethod<[LicenseRequest], string>,
  'getActiveFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getActivePremiumProductNames' : ActorMethod<[], Array<string>>,
  'getAllLicenseBundles' : ActorMethod<[], Array<LicenseBundle>>,
  'getAuditLog' : ActorMethod<[bigint], Array<AuditEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfigurationStatus' : ActorMethod<
    [],
    {
      'stripeConfigured' : boolean,
      'privateKeyPresent' : boolean,
      'resendConfigured' : boolean,
    }
  >,
  'getCoreFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getFeatureImage' : ActorMethod<[string], [] | [Uint8Array | number[]]>,
  'getCustomerEntitlements' : ActorMethod<
    [string],
    Array<EntitlementStatusView>
  >,
  'getEmailAutomationSettings' : ActorMethod<[], EmailAutomationSettings>,
  'getEmailLogs' : ActorMethod<[], Array<EmailLog>>,
  'getEntitlementRegistry' : ActorMethod<[], Array<EntitlementRegistryEntry>>,
  'getEntitlementStatus' : ActorMethod<
    [string, string],
    { 'ok' : EntitlementStatusView } |
      { 'err' : string }
  >,
  'getInstallerChunkMaxBytes' : ActorMethod<[], bigint>,
  /**
   * / Public metadata only (DDR-029) — file names for version display without downloading blobs.
   */
  'getInstallerFileNames' : ActorMethod<
    [],
    { 'windowsFileName' : [] | [string], 'macFileName' : [] | [string] }
  >,
  'getLicenseBundles' : ActorMethod<[], Array<LicenseBundle>>,
  'getLicenseFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getLicenseRecords' : ActorMethod<[], Array<LicenseRecord>>,
  'getLicenseReferenceNames' : ActorMethod<[], Array<string>>,
  'getLicensingPolicy' : ActorMethod<
    [],
    {
      'licenseTermDays' : bigint,
      'activationWindowDays' : bigint,
      'machineBindingAlgorithm' : string,
    }
  >,
  'getMacInstallerFile' : ActorMethod<
    [],
    [] | [{ 'file' : Uint8Array, 'mimeType' : string, 'fileName' : string }]
  >,
  'getMacInstallerMeta' : ActorMethod<[], [] | [InstallerMeta]>,
  'getMyAdminRole' : ActorMethod<[], [] | [string]>,
  'getPremiumFeatures' : ActorMethod<[], Array<LicenseFeature>>,
  'getPremiumPurchases' : ActorMethod<[], Array<PremiumPurchase>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getPublicMacInstallerMeta' : ActorMethod<[], [] | [InstallerMeta]>,
  'getPublicWindowsInstallerMeta' : ActorMethod<[], [] | [InstallerMeta]>,
  'getResendConfiguration' : ActorMethod<[], [] | [ResendConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], Result_1>,
  'getSuperAdminClaimCode' : ActorMethod<[], string>,
  'getTransactionLogs' : ActorMethod<[], Array<TransactionLog>>,
  'getTrialEligibleProductNames' : ActorMethod<[], Array<string>>,
  'getTrialLicenseFile' : ActorMethod<[], [] | [Uint8Array]>,
  'getTrialLicensePayload' : ActorMethod<[string], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[], Array<UserSubmission>>,
  'getWindowsInstallerFile' : ActorMethod<
    [],
    [] | [{ 'file' : Uint8Array, 'mimeType' : string, 'fileName' : string }]
  >,
  'getWindowsInstallerMeta' : ActorMethod<[], [] | [InstallerMeta]>,
  'incrementDownloadCount' : ActorMethod<[string], undefined>,
  'initializeDefaultLicenseBundles' : ActorMethod<[], undefined>,
  'initializeDefaultCoreFeatures' : ActorMethod<[], undefined>,
  'initializeDefaultPremiumFeatures' : ActorMethod<[], undefined>,
  'inviteAdmin' : ActorMethod<[string, string, AdminRole], Result>,
  'isAdminByRole' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'issueTrialLicenseAndEmail' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'listAdmins' : ActorMethod<[], Array<AdminRecordPublic>>,
  'logEmail' : ActorMethod<[string, string, string], undefined>,
  'migrateFeatureNames' : ActorMethod<[], string>,
  'reactivateAdmin' : ActorMethod<[string], Result>,
  'recordLicense' : ActorMethod<
    [string, string, Array<string>, bigint, string],
    undefined
  >,
  'recordPremiumPurchase' : ActorMethod<
    [string, string, bigint, string, string, string, string, Array<string>],
    undefined
  >,
  'regenerateSuperAdminClaimCode' : ActorMethod<[], Result>,
  'removeFeatureImage' : ActorMethod<[string], undefined>,
  'resendPurchaseLicense' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resendTrialLicense' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Admin support: clear machine binding and return entitlement to pending_activation
   * / with a fresh activation window + nonce (so the customer can re-activate on a device).
   * / Does not delete the registry row or linked purchases. One row remains per email.
   */
  'resetEntitlementActivation' : ActorMethod<
    [string],
    { 'ok' : EntitlementStatusView } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendManualLicense' : ActorMethod<
    [string, string, Array<string>],
    EmailSendResult
  >,
  'sendSignedPaidLicense' : ActorMethod<
    [string, string, string, Array<string>],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendSignedTrialLicenseEmail' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'sendTrialLicenseEmail' : ActorMethod<[string, string, string], undefined>,
  'setResendConfiguration' : ActorMethod<[ResendConfiguration], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitUser' : ActorMethod<
    [string, string],
    { 'alreadySubmitted' : { 'email' : string } } |
      { 'newUser' : { 'message' : string } }
  >,
  'testResendConnection' : ActorMethod<[], EmailSendResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminRole' : ActorMethod<[string, AdminRole], Result>,
  'updateBundleStatus' : ActorMethod<[string, boolean], undefined>,
  'updateEmailAutomationSettings' : ActorMethod<
    [EmailAutomationSettings],
    undefined
  >,
  'updateFeatureStatus' : ActorMethod<[string, boolean], undefined>,
  'updateLicenseBundle' : ActorMethod<[LicenseBundle], undefined>,
  'updateLicenseFeature' : ActorMethod<[LicenseFeature], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updatePurchaseFeatures' : ActorMethod<
    [string, Array<string>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateResendServiceName' : ActorMethod<[string], undefined>,
  'uploadFeatureImage' : ActorMethod<[string, Uint8Array], undefined>,
  /**
   * / Legacy single-shot upload — only for files ≤ chunk max. Prefer begin/chunk/finalize for DMG/EXE.
   */
  'uploadMacInstaller' : ActorMethod<[Uint8Array, string], boolean>,
  'uploadMacInstallerChunk' : ActorMethod<[bigint, Uint8Array], Result>,
  'uploadPrivateKeyFile' : ActorMethod<[Uint8Array], undefined>,
  'uploadPrivateKeyPem' : ActorMethod<[string], undefined>,
  'uploadTrialLicenseFile' : ActorMethod<[Uint8Array], undefined>,
  'uploadWindowsInstaller' : ActorMethod<[Uint8Array, string], boolean>,
  'uploadWindowsInstallerChunk' : ActorMethod<[bigint, Uint8Array], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];